### ISSUE TITLE
Fatal error occured...

### ISSUE THREAD

**Issue by notDavid** [cgrossde/Pullover#78] opened 2016-12-21 19:31 UTC
See logs here: https://gist.github.com/notDavid/f1c3ee88c7a02a5b422d8bcae2580aa2

macOS 10.12.2

**Comment by cgrossde** [comment] 2017-02-17 16:44
Thanks for the report, will take a look at it. Duplicate of #63

**Closed by cgrossde** 2017-02-17 16:44 UTC
