### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by highacid** [cgrossde/Pullover#73] opened 2016-10-23 15:59 UTC
[pullover.1.txt](https://github.com/cgrossde/Pullover/files/546442/pullover.1.txt)
here is the log, running OS Sierra.

**Comment by highacid** [comment] 2016-11-01 21:01
[pullover.1.log.txt](https://github.com/cgrossde/Pullover/files/565060/pullover.1.log.txt)
[pullover.2.log.txt](https://github.com/cgrossde/Pullover/files/565062/pullover.2.log.txt)
[pullover.3.log.txt](https://github.com/cgrossde/Pullover/files/565061/pullover.3.log.txt)
[pullover.4.log.txt](https://github.com/cgrossde/Pullover/files/565063/pullover.4.log.txt)
[pullover.5.log.txt](https://github.com/cgrossde/Pullover/files/565064/pullover.5.log.txt)

This is keep repeating.

**Comment by cgrossde** [comment] 2016-11-02 15:21
Duplicate of #63. Will suppress this error once I get the time. It can be ignored.

**Closed by cgrossde** 2016-11-02 15:21 UTC
