### ISSUE TITLE
Uncaught Exception: Error: read ECONNRESET

### ISSUE THREAD

**Issue by ryanerwin** [cgrossde/Pullover#75] opened 2016-12-02 14:17 UTC
Hello,

I'm getting an "Uncaught Exeption: Error: read ECONNRESET" that's come up several times.
I've attached the log files from Appdata/Roaming/Pullover/Logs

In most cases I'm seeing:

```
' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
'Pullover v1.2.0'
'=============== STACK ==============='
'Error: socket hang up
    at createHangUpError (_http_client.js:192:15)
    at TLSSocket.socketOnEnd (_http_client.js:270:23)
    at emitNone (events.js:70:20)
    at TLSSocket.emit (events.js:147:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:375:11)'
'=============== Error Object ==============='
'{ stack: 'Error: socket hang up
    at createHangUpError (_http_client.js:192:15)
    at TLSSocket.socketOnEnd (_http_client.js:270:23)
    at emitNone (events.js:70:20)
    at TLSSocket.emit (events.js:147:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:375:11)', message: 'socket hang up', code: 'ECONNRESET' }'
' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
```

Also, I've also got a Proxy set under Settings > Network & Internet > Proxy > Automatic Proxy Setup, but this seems to be ignored by Pullover.

[pullover.1.log.txt](https://github.com/cgrossde/Pullover/files/627324/pullover.1.log.txt)
[pullover.2.log.txt](https://github.com/cgrossde/Pullover/files/627322/pullover.2.log.txt)
[pullover.3.log.txt](https://github.com/cgrossde/Pullover/files/627323/pullover.3.log.txt)
[pullover.4.log.txt](https://github.com/cgrossde/Pullover/files/627325/pullover.4.log.txt)
[pullover.5.log.txt](https://github.com/cgrossde/Pullover/files/627326/pullover.5.log.txt)

**Comment by genepool99** [comment] 2017-01-19 21:34
I am also getting the same error. Windows 7, pullover 1.2.0:

 

```
Fatal                ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
debug.js:57   Fatal                'Pullover v1.2.0'
debug.js:57   Fatal                '=============== STACK ==============='
debug.js:57   Fatal                'Error: socket hang up
    at createHangUpError (_http_client.js:192:15)
    at TLSSocket.socketOnEnd (_http_client.js:270:23)
    at emitNone (events.js:70:20)
    at TLSSocket.emit (events.js:147:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:375:11)'
debug.js:57   Fatal                '=============== Error Object ==============='
debug.js:57   Fatal                '{ stack: 'Error: socket hang up
    at createHangUpError (_http_client.js:192:15)
    at TLSSocket.socketOnEnd (_http_client.js:270:23)
    at emitNone (events.js:70:20)
    at TLSSocket.emit (events.js:147:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:375:11)', message: 'socket hang up', code: 'ECONNRESET' }'
```

**Comment by cgrossde** [comment] 2017-02-17 16:46
Thanks for the error reports, will take a look at it. Duplicate of #63

**Closed by cgrossde** 2017-02-17 16:46 UTC
