### ISSUE TITLE
Getting 'Fatal Error' crash with 0.3.2

### ISSUE THREAD

**Issue by genepool99** [cgrossde/Pullover#23] opened 2015-05-18 20:56 UTC
Using Win 7 Pro - 64bit 

Here is the log snippet that might be helpful:

```
Mon May 18 2015 13:45:11 GMT-0700 (Pacific Daylight Time)  App      'getMessages - try request'
Mon May 18 2015 13:45:11 GMT-0700 (Pacific Daylight Time)  OpenClient      'OpenClient.prototype.fetchNotifications'
Mon May 18 2015 13:45:12 GMT-0700 (Pacific Daylight Time)  App      'getMessages - successful'
Mon May 18 2015 13:45:12 GMT-0700 (Pacific Daylight Time)  App      'New messages: 1'
Mon May 18 2015 13:45:12 GMT-0700 (Pacific Daylight Time)  OpenClient      'OpenClient.prototype.acknowledgeNotification'
Mon May 18 2015 13:45:25 GMT-0700 (Pacific Daylight Time)  App      ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Mon May 18 2015 13:45:25 GMT-0700 (Pacific Daylight Time)  App      '=============== STACK ==============='
Mon May 18 2015 13:45:25 GMT-0700 (Pacific Daylight Time)  App      'TypeError: Cannot read property \'style\' of null\n    at setStyleOnDomElement (C:\\Users\\avi\\AppData\\Local\\Temp\

\nw5436_16011\\node_modules\\nw-notify\\index.js:479:16)\n    at Window.<anonymous> (C:\\Users\\avi\\AppData\\Local\\Temp\\nw5436_16011\\node_modules\\nw-notify\\index.js:447:4)\n    at emitNone 

(events.js:70:20)\n    at Window.emit (events.js:147:7)\n    at IDWeakMap.global.__nwObjectsRegistry.handleEvent (node.js:786:26)'
Mon May 18 2015 13:45:25 GMT-0700 (Pacific Daylight Time)  App      '=============== Error Object ==============='
Mon May 18 2015 13:45:25 GMT-0700 (Pacific Daylight Time)  App      '{ stack: "TypeError: Cannot read property \'style\' of null\\n    at setStyleOnDomElement (C:\\\\Users\\\\avi\\\\AppData\\\

\Local\\\\Temp\\\\nw5436_16011\\\\node_modules\\\\nw-notify\\\\index.js:479:16)\\n    at Window.<anonymous> (C:\\\\Users\\\\avi\\\\AppData\\\\Local\\\\Temp\\\\nw5436_16011\\\\node_modules\\\\nw-

notify\\\\index.js:447:4)\\n    at emitNone (events.js:70:20)\\n    at Window.emit (events.js:147:7)\\n    at IDWeakMap.global.__nwObjectsRegistry.handleEvent (node.js:786:26)", message: "Cannot 

read property \'style\' of null" }'
Mon May 18 2015 13:45:25 GMT-0700 (Pacific Daylight Time)  App      ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Mon May 18 2015 13:45:25 GMT-0700 (Pacific Daylight Time)  App      'Show Modal'   'Fatal error'   'Pullover encountered a fatal error. Please goto <a onclick="gui.Shell.openExternal

(\'https://github.com/cgrossde/Pullover/issues\');" href="#">Github (Pullover/Issues)</a> create a new issue and post the contents of your logfile: <a onclick="gui.Shell.showItemInFolder(\'C:\\\

\Users\\\\avi\\\\AppData\\\\Roaming\\\\Pullover\\\\pullover.1.log\');" href="#">C:\\Users\\avi\\AppData\\Roaming\\Pullover\\pullover.1.log</a>'   'danger select-text'   [ { text: 'Exit Pullover', 

func: [Function] } ]
Mon May 18 2015 13:45:41 GMT-0700 (Pacific Daylight Time)  OpenClient      'OpenClient.prototype._parseCommand'
Mon May 18 2015 13:45:41 GMT-0700 (Pacific Daylight Time)  OpenClient      'OpenClient.prototype._resetKeepAlive'
```

**Comment by genepool99** [comment] 2015-05-18 22:04
got the error again, here is the log bits:
Mon May 18 2015 14:27:27 GMT-0700 (Pacific Daylight Time)  App      'TypeError: Cannot read property \'style\' of null\n    at setStyleOnDomElement (C:\\Users\\avi\\AppData\\Local\\Temp\\nw15404_550\\node_modules\\nw-notify\\index.js:479:16)\n    at Window.<anonymous> (C:\\Users\\avi\\AppData\\Local\\Temp\\nw15404_550\\node_modules\\nw-notify\\index.js:447:4)\n    at emitNone (events.js:70:20)\n    at Window.emit (events.js:147:7)\n    at IDWeakMap.global.__nwObjectsRegistry.handleEvent (node.js:786:26)'
Mon May 18 2015 14:27:27 GMT-0700 (Pacific Daylight Time)  App      '=============== Error Object ==============='
Mon May 18 2015 14:27:27 GMT-0700 (Pacific Daylight Time)  App      '{ stack: "TypeError: Cannot read property \'style\' of null\\n    at setStyleOnDomElement (C:\\\\Users\\\\avi\\\\AppData\\\\Local\\\\Temp\\\\nw15404_550\\\\node_modules\\\\nw-notify\\\\index.js:479:16)\\n    at Window.<anonymous> (C:\\\\Users\\\\avi\\\\AppData\\\\Local\\\\Temp\\\\nw15404_550\\\\node_modules\\\\nw-notify\\\\index.js:447:4)\\n    at emitNone (events.js:70:20)\\n    at Window.emit (events.js:147:7)\\n    at IDWeakMap.global.__nwObjectsRegistry.handleEvent (node.js:786:26)", message: "Cannot read property \'style\' of null" }'
Mon May 18 2015 14:27:27 GMT-0700 (Pacific Daylight Time)  App      ' - - - - - - - - UNCAUGHT EXCEPTION - - - - - - - - '
Mon May 18 2015 14:27:27 GMT-0700 (Pacific Daylight Time)  App      'Show Modal'   'Fatal error'   'Pullover encountered a fatal error. Please goto <a onclick="gui.Shell.openExternal(\'https://github.com/cgrossde/Pullover/issues\');" href="#">Github (Pullover/Issues)</a> create a new issue and post the contents of your logfile: <a onclick="gui.Shell.showItemInFolder(\'C:\\\\Users\\\\avi\\\\AppData\\\\Roaming\\\\Pullover\\\\pullover.1.log\');" href="#">C:\\Users\\avi\\AppData\\Roaming\\Pullover\\pullover.1.log</a>'   'danger select-text'   [ { text: 'Exit Pullover', func: [Function] } ]

**Comment by cgrossde** [comment] 2015-05-19 16:27
Thanks for posting this. It seems to be an error with the `nw-notify` module. I will take a look at it.

**Comment by cgrossde** [comment] 2015-06-01 09:54
I can't reproduce this error neither could I find a case where `nw-notify` could fail like this. 
@genepool99  Did you experience this bug again? Were there a lot of notifications displayed when the error occurred or only one?

Anyone else having this issue?
Did this happen again?

**Comment by RenaudParis** [comment] 2015-06-14 00:49
I am trying nw-notify and I have this error in my test app, whereas I don't have the error in the nw-sample-apps. I copy/pasted the code from https://www.npmjs.com/package/nw-notify and got the error.

It fails when calling:

```setStyleOnDomElement(config.defaultStyleContainer, container);```

I am on Windows. I debugged the config.templatePath value and got:

```app://host/app/node_modules/nw-notify/notification.html```

If I change it to ```config.templatePath = 'app://app/node_modules/nw-notify/notification.html';``` then it works fine.

Hope this helps.

**Comment by genepool99** [comment] 2015-06-16 19:38
I haven't had the problem in a while. I was likely getting more than one notification when the error happened.

**Comment by cgrossde** [comment] 2015-10-17 11:38
This will likely be resolved by cgrossde/nw-notify#14

**Comment by raffr** [comment] 2015-12-05 12:57
Guys, same here.

In a simple example, i got the same error.


```
//App.js

var nwNotify = require('nw-notify');

nwNotify.setConfig({
    appIcon: nwNotify.getAppPath() + '/assets/img/icon.png',
    displayTime: 6000
});

 nwNotify.setTemplatePath(nwNotify.getAppPath() + 'notification.html');

nwNotify.notify({
    title: 'Some title',
    text:  'Some text'});
```

```
//node_modules/nw-notify/index.js

domElement.style[styleAttr] = styleObj[styleAttr]; //Problem is here

```

**Comment by cgrossde** [comment] 2016-02-01 19:18
@raffr This is a `nw-notify` error. It happens when the template file could not be found. I released a new version yesterday. Please try it out, the error should be gone, you will also be notified now if the template can't be found.

**Comment by cgrossde** [comment] 2016-02-27 15:47
Please try the new alpha, it's a complete rewrite: 
https://github.com/cgrossde/Pullover/releases/tag/1.0.0-alpha.1

**Closed by cgrossde** 2016-02-27 15:47 UTC
Labels: bug, needsFeedback
