### ISSUE TITLE
Fatal error occurred

### ISSUE THREAD

**Issue by realcanadrian** [cgrossde/Pullover#54] opened 2016-05-23 21:38 UTC
The pullover beta 1.0.0-beta.2 on Windows 10 x64 told me to post this here.

[pullover.1.log.zip](https://github.com/cgrossde/Pullover/files/278319/pullover.1.log.zip)

**Comment by cgrossde** [comment] 2016-05-25 22:09
Duplicate of #52

**Closed by cgrossde** 2016-05-25 22:09 UTC
